language: c
dist: trusty

env:
  #- PHP_VERSION=5.2.17 ZTS=yes MIRROR=http://museum.php.net/php5/
  - PHP_VERSION=5.3.29 ZTS=yes
  - PHP_VERSION=5.4.45 ZTS=yes
  - PHP_VERSION=5.5.37 ZTS=yes
  - PHP_VERSION=5.6.30 ZTS=yes
  - PHP_VERSION=5.6.30 ZTS=no

cache:
  directories:
    - $HOME/php_builds

before_install:
  - source travis.sh
  - maybe_install_php $PHP_VERSION $ZTS

install:
  - build $PHP_VERSION $ZTS

script:
  - run_tests $PHP_VERSION $ZTS
